var json = {
	"game1": {
		"title": ["Title", "Rayman Origins"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Platformer"],
		"publisher": ["Publisher", "Ubisoft"],
		"developer": ["Developer", "Ubisoft Montpellier Studios"],
		"completed": ["Completed", "Yes"],
		"purchased": ["Purchase Date", "2012-03-29"],
		"purchased_amount": ["Purchase Amount", "59.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", "Platinum trophy obtained"],
		"favorite": ["Favorite", "Yes"]
	},
	"game2": {
		"title": ["Title", "Dust 514"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Shooter"],
		"publisher": ["Publisher", "CCP"],
		"developer": ["Developer", "CCP"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2012-07-22"],
		"purchased_amount": ["Purchase Amount", "0"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", "Still in beta"],
		"favorite": ["Favorite", "No"]
	},
	"game3": {
		"title": ["Title", "Sound Shapes"],
		"platform" : ["Platform", "PlayStation Vita"],
		"genre": ["Genre", "Platform"],
		"publisher": ["Publisher", "Sony Computer Entertainment America, Inc."],
		"developer": ["Developer", "Queasy Games"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2012-08-10"],
		"purchased_amount": ["Purchase Amount", "39.99"],
		"sold": ["Sold Date", "2012-11-05"],
		"sold_amount": ["Sold Amount", "20"],
		"notes": ["Special Notes", "Cross-buy title"],
		"favorite": ["Favorite", "No"]
	},
	"game4": {
		"title": ["Title", "Darksiders"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "THQ, Inc."],
		"developer": ["Developer", "Vigil Games"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2013-01-10"],
		"purchased_amount": ["Purchase Amount", "0"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", "Cross-buy title"],
		"favorite": ["Favorite", "No"]
	},
	"game4": {
		"title": ["Title", "Heavy Rain"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Adventure"],
		"publisher": ["Publisher", "Sony Computer Entertainment America, Inc."],
		"developer": ["Developer", "Quantic Dream"],
		"completed": ["Completed", "Yes"],
		"purchased": ["Purchase Date", "2010-08-10"],
		"purchased_amount": ["Purchase Amount", "59.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "No"]
	},
	"game5": {
		"title": ["Title", "Armored Core V"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "FromSoftware, Inc."],
		"developer": ["Developer", "FromSoftware, Inc."],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2012-03-20"],
		"purchased_amount": ["Purchase Amount", "59.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "No"]
	},
	"game6": {
		"title": ["Title", "The Darkness II"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Shooter"],
		"publisher": ["Publisher", "2K Games, Inc."],
		"developer": ["Developer", "Digital Extremes, Inc."],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2012-03-10"],
		"purchased_amount": ["Purchase Amount", "9.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "No"]
	},
	"game7": {
		"title": ["Title", "Journey"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "Sony Computer Entertainment America, Inc."],
		"developer": ["Developer", "thatgamecompany, LLC"],
		"completed": ["Completed", "Yes"],
		"purchased": ["Purchase Date", "2012-03-13"],
		"purchased_amount": ["Purchase Amount", "14.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", "Breathtaking"],
		"favorite": ["Favorite", "Yes"]
	},
	"game8": {
		"title": ["Title", "Half-Life 2"],
		"platform" : ["Platform", "PC"],
		"genre": ["Genre", "Shooter"],
		"publisher": ["Publisher", "Sierra Entertainment, Inc."],
		"developer": ["Developer", "Valve Corporation"],
		"completed": ["Completed", "Yes"],
		"purchased": ["Purchase Date", "2004-11-16"],
		"purchased_amount": ["Purchase Amount", "49.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", ""]
	},
	"game9": {
		"title": ["Title", "Mass Effect 3"],
		"platform" : ["Platform", "PC"],
		"genre": ["Genre", "Shooter"],
		"publisher": ["Publisher", "Electronic Arts, Inc."],
		"developer": ["Developer", "BioWare Corporation"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2012-12-13"],
		"purchased_amount": ["Purchase Amount", "29.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", ""]
	},
	"game10": {
		"title": ["Title", "Mass Effect 2"],
		"platform" : ["Platform", "PC"],
		"genre": ["Genre", "Shooter"],
		"publisher": ["Publisher", "Electronic Arts, Inc."],
		"developer": ["Developer", "BioWare Corporation"],
		"completed": ["Completed", "Yes"],
		"purchased": ["Purchase Date", "2011-10-12"],
		"purchased_amount": ["Purchase Amount", "9.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "Yes"]
	},
	"game11": {
		"title": ["Title", "Mass Effect"],
		"platform" : ["Platform", "PC"],
		"genre": ["Genre", "Shooter"],
		"publisher": ["Publisher", "Electronic Arts, Inc."],
		"developer": ["Developer", "BioWare Corporation"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2011-10-12"],
		"purchased_amount": ["Purchase Amount", "7.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "Yes"]
	},
	"game12": {
		"title": ["Title", "Batman: Arkham City"],
		"platform" : ["Platform", "PC"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "Warner Bros. Interactive Entertainment, Inc."],
		"developer": ["Developer", "Rocksteady Studio Ltd."],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2011-10-11"],
		"purchased_amount": ["Purchase Amount", "8.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "Yes"]
	},
	"game13": {
		"title": ["Title", "Batman: Arkham Asylum"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "Warner Bros. Interactive Entertainment, Inc."],
		"developer": ["Developer", "Rocksteady Studio Ltd."],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2010-01-18"],
		"purchased_amount": ["Purchase Amount", "19.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "Yes"]
	},
	"game14": {
		"title": ["Title", "Angry Birds"],
		"platform" : ["Platform", "iOS"],
		"genre": ["Genre", "Strategy"],
		"publisher": ["Publisher", "Clickgamer Technologies, Ltd."],
		"developer": ["Developer", "Rovio Mobile Ltd."],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2009-12-18"],
		"purchased_amount": ["Purchase Amount", ".99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", ""]
	},
	"game15": {
		"title": ["Title", "Spy Mouse"],
		"platform" : ["Platform", "iOS"],
		"genre": ["Genre", "Puzzle"],
		"publisher": ["Publisher", "Firemint"],
		"developer": ["Developer", "Firemint"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2011-11-03"],
		"purchased_amount": ["Purchase Amount", "0"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", "Received free from Starbucks promotion"],
		"favorite": ["Favorite", "No"]
	},
	"game16": {
		"title": ["Title", "Sly Cooper and the Thievius Racoonus"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "Sony Computer Entertainment America, Inc."],
		"developer": ["Developer", "Sucker Punch Productions LLC"],
		"completed": ["Completed", "Yes"],
		"purchased": ["Purchase Date", "2012-08-18"],
		"purchased_amount": ["Purchase Amount", "9.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "Yes"]
	},
	"game17": {
		"title": ["Title", "Sly 2: Band of Thieves"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "Sony Computer Entertainment America, Inc."],
		"developer": ["Developer", "Sucker Punch Productions LLC"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2012-08-18"],
		"purchased_amount": ["Purchase Amount", "9.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "Yes"]
	},
	"game18": {
		"title": ["Title", "Sly 3: Honor Among Thieves"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "Sony Computer Entertainment America, Inc."],
		"developer": ["Developer", "Sucker Punch Productions LLC"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2012-08-18"],
		"purchased_amount": ["Purchase Amount", "9.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "Yes"]
	},
	"game19": {
		"title": ["Title", "Sly Cooper: Thieves in Time"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "Sony Computer Entertainment America, Inc."],
		"developer": ["Developer", "Sanzaru Games"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2013-02-05"],
		"purchased_amount": ["Purchase Amount", "59.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "Yes"]
	},
	"game20": {
		"title": ["Title", "Superbrothers: Sword & Sworcery EP"],
		"platform" : ["Platform", "iOS"],
		"genre": ["Genre", "Adventure"],
		"publisher": ["Publisher", "Capybara Games, Inc."],
		"developer": ["Developer", "Superbrothers, Inc."],
		"completed": ["Completed", "Yes"],
		"purchased": ["Purchase Date", "2011-03-23"],
		"purchased_amount": ["Purchase Amount", "4.99"],
		"sold": ["Sold Date", ""],
		"sold_amount": ["Sold Amount", ""],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", ""]
	}
};