var json = {
	"game1": {
		"title": ["Title", "Rayman Origins"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Platformer"],
		"publisher": ["Publisher", "Ubisoft"],
		"developer": ["Developer", "Ubisoft Montpellier Studios"],
		"completed": ["Completed", "Yes"],
		"purchased": ["Purchase Date", "2012-03-29"],
		"purchased_amount": ["Purchase Amount", "59.99"],
		"sold": ["Sold Date", "n/a"],
		"sold_amount": ["Sold Amount", "n/a"],
		"notes": ["Special Notes", "Platinum trophy obtained"],
		"favorite": ["Favorite", "Yes"]
	},
	"game2": {
		"title": ["Title", "Dust 514"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Shooter"],
		"publisher": ["Publisher", "CCP"],
		"developer": ["Developer", "CCP"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2012-07-22"],
		"purchased_amount": ["Purchase Amount", "0"],
		"sold": ["Sold Date", "n/a"],
		"sold_amount": ["Sold Amount", "n/a"],
		"notes": ["Special Notes", "Still in beta"],
		"favorite": ["Favorite", "No"]
	},
	"game3": {
		"title": ["Title", "Sound Shapes"],
		"platform" : ["Platform", "PlayStation Vita / PSP"],
		"genre": ["Genre", "Platform"],
		"publisher": ["Publisher", "Sony Computer Entertainment America, Inc."],
		"developer": ["Developer", "Queasy Games"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2012-08-10"],
		"purchased_amount": ["Purchase Amount", "39.99"],
		"sold": ["Sold Date", "2012-11-05"],
		"sold_amount": ["Sold Amount", "20"],
		"notes": ["Special Notes", "Cross-buy title"],
		"favorite": ["Favorite", "No"]
	},
	"game4": {
		"title": ["Title", "Darksiders"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "THQ, Inc."],
		"developer": ["Developer", "Vigil Games"],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2013-01-10"],
		"purchased_amount": ["Purchase Amount", "0"],
		"sold": ["Sold Date", "n/a"],
		"sold_amount": ["Sold Amount", "n/a"],
		"notes": ["Special Notes", "Cross-buy title"],
		"favorite": ["Favorite", "No"]
	},
	"game4": {
		"title": ["Title", "Heavy Rain"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Adventure"],
		"publisher": ["Publisher", "Sony Computer Entertainment America, Inc."],
		"developer": ["Developer", "Quantic Dream"],
		"completed": ["Completed", "Yes"],
		"purchased": ["Purchase Date", "2010-08-10"],
		"purchased_amount": ["Purchase Amount", "59.99"],
		"sold": ["Sold Date", "n/a"],
		"sold_amount": ["Sold Amount", "n/a"],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "No"]
	},
	"game5": {
		"title": ["Title", "Armored Core V"],
		"platform" : ["Platform", "PlayStation 3"],
		"genre": ["Genre", "Action"],
		"publisher": ["Publisher", "FromSoftware, Inc."],
		"developer": ["Developer", "FromSoftware, Inc."],
		"completed": ["Completed", "No"],
		"purchased": ["Purchase Date", "2012-03-20"],
		"purchased_amount": ["Purchase Amount", "59.99"],
		"sold": ["Sold Date", "n/a"],
		"sold_amount": ["Sold Amount", "n/a"],
		"notes": ["Special Notes", ""],
		"favorite": ["Favorite", "No"]
	}
};